import { MerkleTreeService } from '../../shield-anchor/src/merkle/merkle-tree.service';
import { StandaloneMerkleVerifier } from '../src/merkle/standalone-merkle-verifier';

describe('Verifier CLI <-> Shield Anchor Cryptographic Round-Trip Test (TUT-05)', () => {
  let anchorMerkle: MerkleTreeService;
  let standaloneVerifier: StandaloneMerkleVerifier;

  beforeAll(() => {
    anchorMerkle = new MerkleTreeService();
    standaloneVerifier = new StandaloneMerkleVerifier();
  });

  describe('Bit-for-Bit Hash & Root Equivalence', () => {
    it('produces identical domain-separated leaf hashes (0x00 prefix)', () => {
      const canonicalLeaf = JSON.stringify({
        tenantId: 'tenant-test-1',
        recordId: 'rec-001',
        contentHash: 'a1b2c3d4e5f6',
      });

      const anchorLeafHash = anchorMerkle.hashLeaf(canonicalLeaf);
      const standaloneLeafHash = standaloneVerifier.hashLeaf(canonicalLeaf);

      expect(standaloneLeafHash.toString('hex')).toBe(
        anchorLeafHash.toString('hex'),
      );
    });

    it('produces identical domain-separated branch hashes (0x01 prefix)', () => {
      const left = Buffer.from(
        '1111111111111111111111111111111111111111111111111111111111111111',
        'hex',
      );
      const right = Buffer.from(
        '2222222222222222222222222222222222222222222222222222222222222222',
        'hex',
      );

      const anchorBranch = anchorMerkle.hashBranch(left, right);
      const standaloneBranch = standaloneVerifier.hashBranch(left, right);

      expect(standaloneBranch.toString('hex')).toBe(
        anchorBranch.toString('hex'),
      );
    });

    const testCounts = [1, 2, 3, 5, 8, 17, 50];

    testCounts.forEach((count) => {
      it(`produces bit-identical Merkle root for ${count} leaves`, () => {
        const leaves = Array.from({ length: count }, (_, i) =>
          JSON.stringify({
            index: i,
            tenantId: 'tenant-crypto-roundtrip',
            payload: `event-content-${i}`,
          }),
        );

        const anchorResult = anchorMerkle.build(leaves);
        const standaloneResult = standaloneVerifier.build(leaves);

        expect(standaloneResult.root).toBe(anchorResult.root);
        expect(standaloneResult.treeProfile).toBe(anchorResult.treeProfile);
        expect(standaloneResult.hashAlgorithm).toBe(anchorResult.hashAlgorithm);
      });
    });
  });

  describe('Inclusion Proof Verification & Tamper Detection', () => {
    it('successfully verifies inclusion proof generated by anchor in standalone verifier', () => {
      const leaves = [
        'evidence-leaf-0',
        'evidence-leaf-1',
        'evidence-leaf-2',
        'evidence-leaf-3',
        'evidence-leaf-4',
      ];

      const anchorTree = anchorMerkle.build(leaves);

      // Verify each leaf with standalone verifier
      leaves.forEach((leaf, idx) => {
        const proof = anchorTree.proofs[idx];
        const isValid = standaloneVerifier.verifyInclusion(
          leaf,
          proof,
          anchorTree.root,
        );
        expect(isValid).toBe(true);
      });
    });

    it('detects byte-tamper on leaf content', () => {
      const leaves = ['evidence-item-A', 'evidence-item-B', 'evidence-item-C'];
      const anchorTree = anchorMerkle.build(leaves);
      const proof = anchorTree.proofs[0];

      // Mutate leaf content
      const tamperedLeaf = 'evidence-item-A-TAMPERED';
      const isValid = standaloneVerifier.verifyInclusion(
        tamperedLeaf,
        proof,
        anchorTree.root,
      );

      expect(isValid).toBe(false);
    });

    it('detects mutation in proof path sibling hash', () => {
      const leaves = ['evidence-item-A', 'evidence-item-B', 'evidence-item-C'];
      const anchorTree = anchorMerkle.build(leaves);
      const corruptedProof = anchorTree.proofs[0].map((step, i) =>
        i === 0
          ? {
              ...step,
              siblingHash:
                'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
            }
          : step,
      );

      const isValid = standaloneVerifier.verifyInclusion(
        leaves[0],
        corruptedProof,
        anchorTree.root,
      );

      expect(isValid).toBe(false);
    });
  });
});
