// Sentinel "tenant" used only for platform-level (roleLevel: PLATFORM) role
// grants — catalog management (permissions, roles) is a platform capability,
// not scoped to any customer tenant. Never a real tenant row.
export const PLATFORM_SCOPE = '00000000-0000-0000-0000-000000000000';

export const PERMISSION_CODES = {
  PLATFORM_PERMISSION_MANAGE: 'platform:permission:manage',
  PLATFORM_ROLE_MANAGE: 'platform:role:manage',
  PLATFORM_TENANT_ONBOARD: 'platform:tenant:onboard',
  PLATFORM_METER_DEFINITION_MANAGE: 'platform:meter-definition:manage',
  PLATFORM_SLA_DEFINITION_MANAGE: 'platform:sla-definition:manage',
  PLATFORM_RESOURCE_DEFINITION_MANAGE: 'platform:resource-definition:manage',
  PLATFORM_CLAIM_MANAGE: 'platform:claim:manage',
  PLATFORM_CLAIM_LEGAL_APPROVE: 'platform:claim:legal-approve',
  PLATFORM_CLAIM_COMPLIANCE_APPROVE: 'platform:claim:compliance-approve',
  PLATFORM_COMMERCIAL_ACCOUNT_MANAGE: 'platform:commercial-account:manage',
  PLATFORM_CATALOG_MANAGE: 'platform:catalog:manage',
  PLATFORM_PRICE_APPROVE: 'platform:price:approve',
  PLATFORM_COMMERCIAL_READINESS_VERIFY: 'platform:commercial-readiness:verify',
  PLATFORM_CONCESSION_MANAGE: 'platform:concession:manage',
  PLATFORM_CONCESSION_APPROVE: 'platform:concession:approve',
  PLATFORM_ASSURANCE_CONTENT_MANAGE: 'platform:assurance-content:manage',
  PLATFORM_ASSURANCE_CONTENT_APPROVE: 'platform:assurance-content:approve',
  TENANT_MEMBER_INVITE: 'tenant:member:invite',
  TENANT_MANAGE: 'tenant:manage',
  TENANT_RESOURCE_READ: 'tenant:resource:read',
  TENANT_RESOURCE_WRITE: 'tenant:resource:write',
  TENANT_COMMERCIAL_ACCOUNT_READ: 'tenant:commercial-account:read',
  TENANT_COMMERCIAL_ACCOUNT_MANAGE: 'tenant:commercial-account:manage',
  TENANT_COMMERCIAL_ACCOUNT_APPROVE: 'tenant:commercial-account:approve',
  TENANT_IR_LEGAL_SENSITIVE_READ: 'tenant:ir-legal-sensitive:read',
  TENANT_IR_LEGAL_SENSITIVE_MANAGE: 'tenant:ir-legal-sensitive:manage',
  TENANT_PROFESSIONAL_SERVICE_READ: 'tenant:professional-service:read',
  TENANT_PROFESSIONAL_SERVICE_MANAGE: 'tenant:professional-service:manage',
  TENANT_PROFESSIONAL_SERVICE_APPROVE: 'tenant:professional-service:approve',
  TENANT_AI_GOVERNANCE_READ: 'tenant:ai-governance:read',
  TENANT_AI_GOVERNANCE_MANAGE: 'tenant:ai-governance:manage',
  TENANT_AI_GOVERNANCE_APPROVE: 'tenant:ai-governance:approve',
  TENANT_PAYMENT_CREATE: 'tenant:payment:create',
  TENANT_REFUND_MANAGE: 'tenant:refund:manage',
  TENANT_PARTNER_DELEGATION_READ: 'tenant:partner-delegation:read',
  TENANT_PARTNER_DELEGATION_MANAGE: 'tenant:partner-delegation:manage',
  TENANT_PARTNER_DELEGATION_USE: 'tenant:partner-delegation:use',
  TENANT_CORPORATE_TRANSFER_MANAGE: 'tenant:corporate-transfer:manage',
  TENANT_CORPORATE_TRANSFER_APPROVE: 'tenant:corporate-transfer:approve',
  TENANT_IDENTITY_PROVIDER_MANAGE: 'tenant:identity-provider:manage',
  TENANT_OFFBOARDING_START: 'tenant_offboarding:start',
  DELETION_REQUEST: 'deletion:request',
  LEGAL_HOLD_CREATE: 'legal_hold:create',
  DETECTION_MANAGE: 'platform:detection:manage',
} as const;
